name = "potato"
port = 7777
host = "*.localhost"
socket_file = "./tmp/potatoverse.sock"
dev_mode = false
# if starts with $ then it will be treated as an environment variable
master_secret = "$POTATO_MASTER_SECRET" 
debug = true
working_dir = "./tmp"

rendezvous_urls = [
    { url = "http://localhost:8080", provider = "http", priority = 1, simple_mode = true },
]

[[buddies]]
pubkey = "1234567890"
url = "http://localhost:8080"
priority = 1
provider = "http"
pre_connect = true




[backup-config]
full-snapshot-interval = "1h"
delta-snapshot-interval = "10m"
delete-interval = "1h"

# repo array
[[repo]]
url = "https://store.potatoverse.com/package_index.json"
type = "http"
slug = "official"
name = "Official Potato Store"

[[repo]]
name = "Development Packages"
type = "embeded"
slug = "dev"


[mailer]
type = "stdio"