name = "Simple TODO"
info = "Todo list app to manage your tasks."
slug = "simple-todo"
tags = ["productivity", "personal"]
format_version = "0.0.1"
author_name = "John Doe"
author_email = "john.doe@example.com"
author_site = "https://example.com"
source_code = "https://github.com/john-doe/simple-todo"
license = "MIT"
version = "0.0.1"
update_url = "https://github.com/john-doe/simple-todo/refs/heads/main/releases.json"

[[artifacts]]
namespace = "simple-todo"
kind = "space"
executor_type = "luaz"
server_file = "server.lua"
route_options = { serve_folder = "public", force_html_extension = false, force_index_html_file = false }
mcp_options = { enabled = true, definition_file = "mcp.json" }
dev_serve_port = 7778

[dev_options]
server_url = "http://localhost:7777"
# if starts with $ then it will be treated as an environment variable
token = "xxxx"
token_env = "POTATO_DEV_TOKEN"

[packaging]
output_zip_file="simple-todo.zip"
include_files = [
    "public/**/*",
    "server.lua",
    "mcp.json"
]
exclude_files = [
    "public/node_modules/**/*",
    "public/package-lock.json",
    "public/package.json",
    "public/package-lock.json",
]